RepositorioESI/esi/apps/foro/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = "foro"

urlpatterns = [
	path('admin/', admin.site.urls),
	path('Crear/', views.Crear.as_view(), name="crear"),
	#path('Listar/', views.Listar.as_view(), name="listar"),
	path('Listar/', views.listing, name="listar"),
	#path('Buscar/', views.buscar, name="buscar" ),
	path('Detalle/<int:pk>', views.PostDetail.as_view(),name = 'detalle'),
	path('Agregar/<int:pk>', views.agregar, name='agregar'),



]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

RepositorioESI/esi/esi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth
from django.contrib import admin

from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Home,name="home"),
    #path('noticias/',views.Noticias,name="noticias"),
    path('legal/',views.Legal,name="legal"),
    path('Login',auth.LoginView.as_view(template_name  = "usuarios/login.html"), name="login"),
    path('Logout',auth.LogoutView.as_view(), name="logout"),


    path('foro/',include('apps.foro.urls')),
    path('usuarios/',include('apps.usuarios.urls')),
    path('noticias/', include('apps.noticias.urls')),
    path('mitos/', include('apps.myv.urls'))
]


if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

RepositorioESI/esi/apps/foro/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings

class Tematica(models.Model):
    nombre = models.CharField(max_length=60)

    def __str__(self):
        return self.nombre



class Post(models.Model):
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=200)
    texto = models.TextField()
    fecha_publicacion = models.DateTimeField(default=timezone.now)
    tematica = models.ForeignKey(Tematica, related_name='miTematica', null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.titulo


class Comentario(models.Model):
    post = models.ForeignKey('foro.Post', on_delete=models.CASCADE, related_name='comentarios')
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)
    mensaje = models.TextField()
    fecha_creacion = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.mensaje

RepositorioESI/esi/apps/foro/forms.py
from django import forms
from .models import Post, Comentario


class AltaPost(forms.ModelForm):

    class Meta:
        model = Post
        fields = '__all__'
        exclude = ['autor']

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comentario
        fields = ('mensaje',)
        exclude = ['usuario']

RepositorioESI/esi/apps/foro/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import AltaPost , CommentForm
from .models import Post, Tematica, Comentario
from django.views.generic import CreateView, DetailView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse,Http404
from django.db.models import Q
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

import json



#--------------Vista basada en clases-----------------
class Crear(LoginRequiredMixin,CreateView):
    model = Post
    form_class = AltaPost
    template_name = 'foro/crear.html'
    success_url = reverse_lazy('foro:listar')
    def form_valid(self, form):
        p = form.save(commit = False)
        p.autor = self.request.user
        p.save()
        return redirect(self.success_url)



#class Listar(ListView):
#    model = Post
#    template_name = 'foro/listar.html'


class PostDetail(DetailView):
    model = Post
    template_name = 'foro/detalle.html'


#------------------Funciones-------------------

def listing(request):
    queryset = request.GET.get("buscar")
    posts = Post.objects.all().order_by('-fecha_publicacion')
    if queryset:
        posts = Post.objects.filter(
            Q(titulo__icontains = queryset) |
            Q(texto__icontains = queryset)
        ).distinct()

    paginator = Paginator(posts,3)
    page_number = request.GET.get('page')
    posts = paginator.get_page(page_number)

    return render(request, 'foro/listar.html', {'posts': posts})


'''
def buscar(request):
    context = {}
    tematicas = Tematica.objects.all()
    context['tematica'] = tematicas
    id_tem = request.GET.get('buscar', None)

    if id_tem:
        resultado = Post.objects.filter(tematica = id_tem).order_by('-fecha_publicacion')
        context['posteos'] = resultado

    else:
        todos = Post.objects.all().order_by('-fecha_publicacion')
        context['posteos'] = todos

    return render(request, 'foro/buscar.html',context )
'''

@login_required
def agregar(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            Comentario = form.save(commit=False)
            Comentario.usuario = request.user
            Comentario.post = post
            Comentario.save()
            return redirect('foro:detalle', pk=pk)
    else:
        form = CommentForm()
    return render(request, 'foro/agregarcomentario.html', {'form': form})

RepositorioESI/esi/templates/foro/agregarcomentario.html
{% extends 'layout.html' %}

{% block content %}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="h1">Nuevo Comentario</h1>
   <div class="tarjeta">
    <form method="POST"  class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="boton">Comentar</button>
    </form>
</div>
</div>


{% endblock %}
</div>

RepositorioESI/esi/templates/foro/buscar.html
{% extends 'layout.html'%}
{%block content%}
<<<<<<< HEAD

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">TEMATICAS</h1>
    <hr>
<form method="GET">
 <select name="buscar">
  {% for t in tematica %}
 <option value="{{t.id}}">{{t.nombre}}</option>
  {% endfor %}
</select>
<button class="btn btn-primary" type="submit">Buscar</button>
</form>

<p class="lead"><a class="boton" href="{% url 'foro:listar' %}" style=""> Volver </a></p>

{% for p in posteos %}

<h3>{{p.titulo}}</h3>

<p>{{p.texto|truncatechars:50}}</p>

<a href="{% url 'foro:detalle' p.id %}">Ver Más</a>


{% endfor %}

</div>

</div>

  {%endblock%}




<<!-- WARNING:
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">FORO</h1>
              <form method="GET">
                <select name="buscar">
                  {% for t in tematica %}
                    <option>{{t.nombre}}</option>
                  {% endfor %}
                </select>
                <button type="submit">Buscar</button>
                {% for p in object_list%}
                  {% if p.tematica == "submit"%}
                      <div class="card" style="width: 18rem;">
                      <div class="card-body">
                        <h5 class="card-title">{{p.titulo}}</h5>
                        <p class="card-text">{{p.texto}}</p>
                        <a href="{% url 'foro:detalle' p.id %}" class="btn btn-primary">Ver</a>
                          </form>
                  {% endif %}
                {% endfor %}

          </div>
        </div>
 -->

=======
>>>>>>> 0724e235c877f1ff245ed6ca36f146e56d44c164
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">FORO</h1>
            <form method="GET">
              <select name="buscar">
                {% for t in tematica %}
                  <option>{{t.nombre}}</option>
                {% endfor %}
              </select>
              <button type="submit">Buscar</button>
              {% for p in object_list%}
                {% if p.tematica == "submit"%}
                    <div class="card" style="width: 18rem;">
                    <div class="card-body">
                      <h5 class="card-title">{{p.titulo}}</h5>
                      <p class="card-text">{{p.texto}}</p>
                      <a href="{% url 'foro:detalle' p.id %}" class="btn btn-primary">Ver</a>
                        </form>
                {% endif %}
              {% endfor %}

        </div>
      </div>
    {% endfor %}
<<<<<<< HEAD

  {%endblock%}

=======
>>>>>>> 0724e235c877f1ff245ed6ca36f146e56d44c164

  {%endblock%}

RepositorioESI/esi/templates/foro/crear.html
{% extends 'layout.html'%}
{%block content%}
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="h1">CREAR POSTEO</h1>
      <div class="tarjeta">
        <form id="form" method='POST'>{%csrf_token%}
          {{form.as_p}}
          <input class="boton" type="submit" name="" value="ENVIAR">
        </form>
      </div>
      </div>

  {% endblock %}
    </div>

RepositorioESI/esi/templates/foro/detalle.html
{% extends 'layout.html'%}
{% block content %}
<! JUMBOTON ->
<div class="jumbotron">
  <div class="container">
    <h3 class="h1"><strong>{{object.titulo}}</strong></h3>
    <br>
    <p id="format2">{{object.fecha_publicacion| date }}</p>
    <br>
    <p id="format2">{{object.texto}}</p>
    <br>

    <hr>

  <a class="btn btn-primary" id="boton-blanco-com" href="{% url 'foro:agregar' post.id %}">Agregar Comentario</a>

  <h3 id="format2">Comentarios</h3>
  <hr>
    {% for comment in post.comentarios.all %}
    <div class="comment">
        <div id="format2">{{ comment.fecha_creacion| date}}</div>
        <p id="format2"><strong>{{ comment.usuario }}</strong></p>
        <p id="format2">{{ comment.mensaje}}</p>
        <hr>
    </div>
    {% empty %}

    <p id="format2">No hay comentarios</p>

    {% endfor %}

    <p class="lead"><a class="btn btn-primary" id="boton-blanco" href="{% url 'foro:listar' %}" style=""> Volver </a></p>
</div>
{% endblock %}
</div>

RepositorioESI/esi/templates/foro/listar.html
{% extends 'layout.html'%}
{%block content%}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="h1">FORO</h1>
      <a id="boton-blanco" type="button" href="{% url 'foro:crear' %}"> CREA TU POSTEO </a><br>

      <br>
    <div class="container">
      <div class="row">
        <div class="col-md-12 search">
          <form method="get">
            <div id="custom-search-input">
              <div class="input-group col-md-12">
                <input id="boton-blanco" type="text" class="form-control" placeholder="Buscar.." name="buscar" value="{{ request.GET.buscar }}">
                <span class="input-group-list">
                  <i class="icon icon-search"></i>
                  <button type="submit" id="boton-blanco">Buscar</button>
                </span>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
<hr>

  {% if posts %}
      {% for p in posts %}
        <br>
        <div class="tarjeta">
            <h3><strong>{{p.titulo}}</strong></h3>
            <p>{{p.texto|truncatechars:50}}</p>
            <a href="{% url 'foro:detalle' p.id %}" class="boton">Ver Más</a>
        </div>

      {% empty %}
        <h5 id="format2"><strong>¡No hay posteos!</strong></h5>
      {%endfor%}
  {% else %}
      <h5 id="format2"><strong>¡No se encontaron coincidencias!</strong></h5>
  {% endif %}

  <hr>

    <div class="pagination">
        <span class="step-links">
            {% if posts.has_previous %}

                <a type="button" class="btn btn-primary btn-sm" id="boton-blanco" href="?page=1">&laquo; Primero</a>
                <a type="button" class="btn btn-primary btn-sm" id="boton-blanco" href="?page={{ posts.previous_page_number }}">Anterior</a>
            {% endif %}

            <span class="current" style="color:white">
              | Pagina {{ posts.number }} de {{ posts.paginator.num_pages }} |
            </span>

            {% if posts.has_next %}
                <a type="button" class="btn btn-primary btn-sm" id="boton-blanco" href="?page={{ posts.next_page_number }}">Siguiente</a>
                <a type="button" class="btn btn-primary btn-sm" id="boton-blanco" href="?page={{ posts.paginator.num_pages }}">Último &raquo;</a>
            {% endif %}
        </span>
    </div>
  </div>

{%endblock%}
</div>