RepositorioESI/esi/apps/myv/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import DetailView
from django.urls import path
from . import views

app_name = "myv"

urlpatterns = [
	path('admin/', admin.site.urls),
	path('mitos/', views.Listar_myv, name="mitos"),
    path('detalles/<int:pk>', views.Detalles_myv.as_view(), name = 'detalles'),

]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

RepositorioESI/esi/esi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth
from django.contrib import admin

from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Home,name="home"),
    #path('noticias/',views.Noticias,name="noticias"),
    path('legal/',views.Legal,name="legal"),
    path('Login',auth.LoginView.as_view(template_name  = "usuarios/login.html"), name="login"),
    path('Logout',auth.LogoutView.as_view(), name="logout"),


    path('foro/',include('apps.foro.urls')),
    path('usuarios/',include('apps.usuarios.urls')),
    path('noticias/', include('apps.noticias.urls')),
    path('mitos/', include('apps.myv.urls'))
]


if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

RepositorioESI/esi/apps/myv/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings



# Create your models here.
class Verdad(models.Model):
    tematicas = (
        ('metodos_anticonceptivos', 'Metodos anticonceptivos'),
        ('masculinidades', 'Masculinidades'),
        ('relaciones_sexuales', 'Relaciones sexuales'),
        ('noviazgo', 'Noviazgo'),
        ('violencia', 'Violencia'),
        ('feminismo', "Feminismo"),
        ('ETS', 'Enfermedades de transmisión sexual'),
        ('ESI', 'Educación Sexual')
    )
    topic = models.CharField(max_length=30,
                  choices=tematicas,
                  default="feminismo")
    title = models.CharField(max_length=200)
    description = models.TextField()
    imagen = models.ImageField()
    verdad = models.TextField()
    mito = models.TextField()
    conclusion = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return self.title

RepositorioESI/esi/apps/myv/views.py
from django.shortcuts import render
from .models import Verdad
from django.views.generic.list import ListView
from django.views.generic import DetailView


# Create your views here.
class Mitos(ListView):
	model = Verdad
	template_name = 'myv/mitos.html'

def Listar_myv(request):
    context = {}
    myv = Verdad.objects.all()
    context['myv'] = myv
    return render(request, 'myv/mitos.html', context)

class Detalles_myv(DetailView):
    model = Verdad
    template_name = 'myv/detalles.html'

RepositorioESI/esi/templates/myv/detalles.html
{% extends "layout.html"%}
{% block content %}
<! JUMBOTON ->
{% load static %}
<link rel="stylesheet" href="{% static 'css/myv.css'%}">
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="h1">Mitos y Verdades</h1>
    <p id="format"> Aunque vivimos en la era de la información y muchas veces creemos 'saberlo todo', tradicionalmente los temas relacionados <br>
                    a la sexualidad de las personas, fueron considerados tabú o del ámbito privado. Por suerte, las cosas han cambiado y <br>
                    estamos acá para acompañar esos cambios. En esta sección te proponemos derribar los mitos que existen en torno a la ESI <br>
                    <strong>¡APRENDAMOS JUNTXS!</strong>
    </p>
    <section id = "principal">
      <section class = "myv">
        <article class="">
        <h5 class="titulo-post">{{object.title}}</h5>
        <p class = "descripcion">{{object.description}}</p>
        </article>
        <table class = "tabla">
            <tr class = "encabezados-tabla">
                <th style="width:120px;" class="encabezado-verdad">Verdad</th>
                <th style="width:5px;" class="encabezado-vs">VS.</th>
                <th style="width:120px;" class="encabezado-mito">Mito</th>
            </tr>
            <tr>
                <td style="width:120px;">{{object.verdad}}</td>
                <td style="width:5px;"></td>
                <td style="width:120px;">{{object.mito}}</td>
            </tr>
        </table>
        <article class = "conclusion">
            <h5>Resumiendo...</h5>
            <p>{{object.conclusion}}</p>

        </article>
      </section>
            <a href="{% url 'myv:mitos' %}" class="btn btn-primary" id="boton-blanco">Volver</a>
  </section>
  </div>
</div>
<! FIN
{% endblock %}

RepositorioESI/esi/templates/myv/mitos.html
{% extends "layout.html"%}
{% block content %}
<! JUMBOTON ->
{% load static %}
<link rel="stylesheet" href="{% static 'css/myv.css'%}">
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="h1">Mitos y Verdades</h1>
    <p id="format">Aunque vivimos en la era de la información y muchas veces creemos 'saberlo todo', tradicionalmente los temas relacionados <br>
                    a la sexualidad de las personas, fueron considerados tabú o del ámbito privado. Por suerte, las cosas han cambiado y <br>
                    estamos acá para acompañar esos cambios. En esta sección te proponemos derribar los mitos que existen en torno a la ESI <br>
                    <strong>¡APRENDAMOS JUNTXS!</strong>
    </p>
    <section id = "principal">
      <section id = "publicaciones">
        {% for v in myv %}
        <article class="myv">
        <a href="{% url 'myv:detalles' v.id %}" class="enlace-post"><h5 class="titulo-post">{{v.title}}</h5></a>
        <img src="{{v.imagen.url}}" width="200" height="200" alt="Imagen del post" class = img-post>
        <p class = "descripcion">{{v.description}}</p>
        </article>
        {% endfor %}
      </section>
  </section>
  </div>
</div>
<! FIN
{% endblock %}