RepositorioESI/esi/apps/foro/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = "foro"

urlpatterns = [
	path('admin/', admin.site.urls),
	path('Crear/', views.Crear.as_view(), name="crear"),
	#path('Listar/', views.Listar.as_view(), name="listar"),
	path('Listar/', views.listing, name="listar"),
	#path('Buscar/', views.buscar, name="buscar" ),
	path('Detalle/<int:pk>', views.PostDetail.as_view(),name = 'detalle'),
	path('Agregar/<int:pk>', views.agregar, name='agregar'),



]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

RepositorioESI/esi/apps/myv/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import DetailView
from django.urls import path
from . import views

app_name = "myv"

urlpatterns = [
	path('admin/', admin.site.urls),
	path('mitos/', views.Listar_myv, name="mitos"),
    path('detalles/<int:pk>', views.Detalles_myv.as_view(), name = 'detalles'),

]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

RepositorioESI/esi/apps/noticias/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name= "noticias"

urlpatterns = [
	path('admin/', admin.site.urls),

	path('Notas/',views.ListarNoticias, name='Notas'),
    path('detalles/<int:pk>', views.NewDetail.as_view(), name = 'detalles')



]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

RepositorioESI/esi/apps/usuarios/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name="usuarios"

urlpatterns = [
	path('admin/', admin.site.urls),
	path('Registrar/', views.RegistroUsuario.as_view(), name = "registrar"),


]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

RepositorioESI/esi/esi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth
from django.contrib import admin

from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Home,name="home"),
    #path('noticias/',views.Noticias,name="noticias"),
    path('legal/',views.Legal,name="legal"),
    path('Login',auth.LoginView.as_view(template_name  = "usuarios/login.html"), name="login"),
    path('Logout',auth.LogoutView.as_view(), name="logout"),


    path('foro/',include('apps.foro.urls')),
    path('usuarios/',include('apps.usuarios.urls')),
    path('noticias/', include('apps.noticias.urls')),
    path('mitos/', include('apps.myv.urls'))
]


if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

RepositorioESI/esi/apps/foro/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings

class Tematica(models.Model):
    nombre = models.CharField(max_length=60)

    def __str__(self):
        return self.nombre



class Post(models.Model):
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=200)
    texto = models.TextField()
    fecha_publicacion = models.DateTimeField(default=timezone.now)
    tematica = models.ForeignKey(Tematica, related_name='miTematica', null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.titulo


class Comentario(models.Model):
    post = models.ForeignKey('foro.Post', on_delete=models.CASCADE, related_name='comentarios')
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)
    mensaje = models.TextField()
    fecha_creacion = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.mensaje

RepositorioESI/esi/apps/noticias/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.contrib import admin
from ckeditor.fields import RichTextField
from datetime import datetime
from django.utils.functional import lazy
from django.utils.timezone import localtime, now




class New(models.Model):
	titulo = models.CharField('titulo de la noticia',max_length=200)
	autor = models.CharField('autor',max_length=200)
	copete = models.TextField('copete')
	cuerpo = RichTextField('texo')
	imagen = models.URLField('imagen')
	fecha_publicacion = models.DateTimeField('fecha de la publicacion',editable=True, auto_now_add=True, auto_now=False)
	fuente = models.URLField('fuente URL',max_length=400)

	def __str__(self):
		return self.titulo

RepositorioESI/esi/apps/foro/forms.py
from django import forms
from .models import Post, Comentario


class AltaPost(forms.ModelForm):

    class Meta:
        model = Post
        fields = '__all__'
        exclude = ['autor']

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comentario
        fields = ('mensaje',)
        exclude = ['usuario']

RepositorioESI/esi/apps/foro/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import AltaPost , CommentForm
from .models import Post, Tematica, Comentario
from django.views.generic import CreateView, DetailView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse,Http404
from django.db.models import Q
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

import json



#--------------Vista basada en clases-----------------
class Crear(LoginRequiredMixin,CreateView):
    model = Post
    form_class = AltaPost
    template_name = 'foro/crear.html'
    success_url = reverse_lazy('foro:listar')
    def form_valid(self, form):
        p = form.save(commit = False)
        p.autor = self.request.user
        p.save()
        return redirect(self.success_url)



#class Listar(ListView):
#    model = Post
#    template_name = 'foro/listar.html'


class PostDetail(DetailView):
    model = Post
    template_name = 'foro/detalle.html'


#------------------Funciones-------------------

def listing(request):
    queryset = request.GET.get("buscar")
    posts = Post.objects.all().order_by('-fecha_publicacion')
    if queryset:
        posts = Post.objects.filter(
            Q(titulo__icontains = queryset) |
            Q(texto__icontains = queryset)
        ).distinct()

    paginator = Paginator(posts,3)
    page_number = request.GET.get('page')
    posts = paginator.get_page(page_number)

    return render(request, 'foro/listar.html', {'posts': posts})


'''
def buscar(request):
    context = {}
    tematicas = Tematica.objects.all()
    context['tematica'] = tematicas
    id_tem = request.GET.get('buscar', None)

    if id_tem:
        resultado = Post.objects.filter(tematica = id_tem).order_by('-fecha_publicacion')
        context['posteos'] = resultado

    else:
        todos = Post.objects.all().order_by('-fecha_publicacion')
        context['posteos'] = todos

    return render(request, 'foro/buscar.html',context )
'''

@login_required
def agregar(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            Comentario = form.save(commit=False)
            Comentario.usuario = request.user
            Comentario.post = post
            Comentario.save()
            return redirect('foro:detalle', pk=pk)
    else:
        form = CommentForm()
    return render(request, 'foro/agregarcomentario.html', {'form': form})

RepositorioESI/esi/apps/noticias/views.py
from django.shortcuts import render
from .models import New
from django.views.generic import CreateView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from django.views.generic import DetailView
from datetime import datetime
# Create your views here.

class Noticia(ListView):
	model = New
	template_name = 'noticias.html'

def ListarNoticias(request):
    context = {}
    noticias = New.objects.all()
    context['noticias'] = noticias
    return render(request, 'noticias/nota.html', context)

class NewDetail(DetailView):
    model = New
    template_name = 'noticias/detalles.html'

RepositorioESI/esi/templates/foro.html
{% extends "layout.html"%}

{% block content %}
<! JUMBOTON ->
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">FORO</h1>
    <p class="lead">portal del foro</p>
  </div>
</div>
<! FIN
{% endblock %}

RepositorioESI/esi/templates/home.html
{% extends "layout.html"%}

{% block content %}
<! JUMBOTON ->

<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="media/PORTADA.png" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="media/PORTADA.png" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="media/PORTADA.png" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<br>
<br>


<div class="container">
    <div class="row">
        <div class="col-3">
            <div class="card">
                <div class="card-body">
                  <h3><strong>Últimas Noticias</strong></h3>
                  {% for n in noticias %}
                  <a href="{% url 'noticias:detalles' n.id %}">* {{n.titulo|truncatechars:50}}</a><br>
                  <hr>
                  {% endfor %}
                </div>
            </div>
        </div>

        <br>
        <br>
        
        <div class="col-6">
            <div class="row justify-content-center display-flex-wrap">
                <div class="col-6 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <a class="nav-link" href="{% url 'noticias:Notas' %}">Noticias</a>
                        </div>
                    </div>
                </div>
                <div class="col-6 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <a class="nav-link" href="{% url 'myv:mitos' %}">Mitos y verdades</a>
                        </div>
                    </div>
                </div>

            </div>



            <div class="row justify-content-center display-flex-wrap margin-top: 20px">
                <div class="col-6 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <a class="nav-link" href="{% url 'legal' %}">Leyes </a>
                        </div>
                    </div>
                </div>

                <div class="col-6 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <a class="nav-link" href="{% url 'foro:listar' %}">Foro</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-3">
          <div class="tarjeta-inicio">
            <div class="card">
                <div class="card-body" style="background-color:#822f77">
                  <h3><strong>Últimos Posteos</strong></h3>
                  {% for p in posts %}
                    <a href="{% url 'foro:detalle' p.id %}"><strong>{{p.titulo}}</strong></a><br>
                    {{p.texto|truncatechars:50}}
                    <hr>
                  {% endfor %}
                </div>
            </div>
        </div>
      </div>
    </div>
</div>

<! FIN
{% endblock %}

RepositorioESI/esi/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial*scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Educación Sexual Integral</title>
	<link rel="icon" href="{% static 'icono/LOGO.ico'%}">
	<!bootstrap->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<!fin->
	<!CSS->
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;1,900&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/main2.css'%}">
	<!FIN->
</head>
<body>
	<! NAVEGADOR BARRA ->
	<nav class="navbar navbar-expand-lg" style="background-color:white">
		<a class="botonEsi" href="{% url 'home' %}">#ESI</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
	</button>
		<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
		<div class="navbar-nav">
				<a class="boton" href="{% url 'noticias:Notas' %}">Noticias</a>
				<a class="boton" href="{% url 'myv:mitos' %}">Mitos y Verdades</a>
				<a class="boton" href="{% url 'foro:listar' %}">Foro</a>
				<a class="boton" href="{% url 'legal' %}">Legales</a>
		</div>
		</div>
				{% if user.is_authenticated%}
						<h5 class="boton">Hola {{user.username}}</h5>
						<a class="boton" href="{% url 'logout' %}">Cerrar Sesión <span class="sr-only">(current)</span></a>
				{% else %}
			  		<a class="boton" href="{% url 'login' %}">Iniciar Sesión <span class="sr-only">(current)</span></a>
						<a class="boton" href="{% url 'usuarios:registrar' %}">Registrar <span class="sr-only">(current)</span></a>
				{% endif %}
</nav>
	<!NAVBAR->
	<div class="container p-4">
	{% block content %}

	{% endblock %}
	</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</body>
	<footer class="footer">
            <br>
            <a id="nav" href="https://www.instagram.com/esiparatodxs" target="_blank"><i class="fab fa-instagram"></i></a>
            <a id="nav" href="https://www.twitter.com/esiparatodxs" target="_blank"><i class="fab fa-twitter"></i></a>
            <a id="nav" href="https://www.facebook.com/esiparatodxs" target="_blank"><i class="fab fa-facebook"></i></a>
            <h5>  Grupo 5 - INFORMATORIO Quarantine Edition 2020</h5>
						  <h5> @ Derechos Reservados </h5>
            <br>
        </footer>
</html>

RepositorioESI/esi/templates/noticias.html
{% extends "layout.html"%}

{% block content %}
<! JUMBOTON ->
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">NOTICIAS</h1>
    <p class="lead">portal</p>
  </div>
</div>
<! FIN
{% endblock %}
		

RepositorioESI/esi/templates/post_list.html
{% extends 'layout.html' %}

{% block contenido %}
		<div>
		    <h1><a href="/">POSTEOS</a></h1>
		</div>

		{% for post in posts %}
		    <div>
		        <p> publicado: {{ post.fecha_publicacion }}</p>
		        <h2><a href="">{{ post.titulo }}</a></h2>
		        <p>{{ post.texto|linebreaksbr }}</p>
		    </div>
		{% endfor %}
{% endblock %}